In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
mouse_drug_data_to_load = "data/mouse_drug_data.csv"
clinical_trial_data_to_load = "data/clinicaltrial_data.csv"

# Read the Mouse and Drug Data and the Clinical Trial Data
df1 = pd.read_csv(mouse_drug_data_to_load)
df2 = pd.read_csv(clinical_trial_data_to_load)

# Combine the data into a single dataset
df = df1.merge(df2, on="Mouse ID")

# Display the data table for preview
df.head(10)

  Mouse ID      Drug  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     f234  Stelasyn          0           45.000000                 0
1     f234  Stelasyn          5           47.313491                 0
2     f234  Stelasyn         10           47.904324                 0
3     f234  Stelasyn         15           48.735197                 1
4     f234  Stelasyn         20           51.112713                 2
5     f234  Stelasyn         25           52.178602                 2
6     f234  Stelasyn         30           56.873817                 2
7     f234  Stelasyn         35           57.748758                 2
8     x402  Stelasyn          0           45.000000                 0
9     x402  Stelasyn          5           46.327570                 1

## Tumor Response to Treatment

In [2]:
# Store the Mean Tumor Volume Data Grouped by Drug and Timepoint 

mean_drug_grp = df.groupby(["Drug", "Timepoint"])["Tumor Volume (mm3)"].mean().reset_index()

# Convert to DataFrame
mean_drug_df = pd.DataFrame(mean_drug_grp)

# Preview DataFrame
mean_drug_df.head(50)

         Drug  Timepoint  Tumor Volume (mm3)
0   Capomulin          0           45.000000
1   Capomulin          5           44.266086
2   Capomulin         10           43.084291
3   Capomulin         15           42.064317
4   Capomulin         20           40.716325
5   Capomulin         25           39.939528
6   Capomulin         30           38.769339
7   Capomulin         35           37.816839
8   Capomulin         40           36.958001
9   Capomulin         45           36.236114
10   Ceftamin          0           45.000000
11   Ceftamin          5           46.503051
12   Ceftamin         10           48.285125
13   Ceftamin         15           50.094055
14   Ceftamin         20           52.157049
15   Ceftamin         25           54.287674
16   Ceftamin         30           56.769517
17   Ceftamin         35           58.827548
18   Ceftamin         40           61.467895
19   Ceftamin         45           64.132421
20  Infubinol          0           45.000000
21  Infubinol          5           47.062001
22  Infubinol         10           49.403909
23  Infubinol         15           51.296397
24  Infubinol         20           53.197691
25  Infubinol         25           55.715252
26  Infubinol         30           58.299397
27  Infubinol         35           60.742461
28  Infubinol         40           63.162824
29  Infubinol         45           65.755562
30   Ketapril          0           45.000000
31   Ketapril          5           47.389175
32   Ketapril         10           49.582269
33   Ketapril         15           52.399974
34   Ketapril         20           54.920935
35   Ketapril         25           57.678982
36   Ketapril         30           60.994507
37   Ketapril         35           63.371686
38   Ketapril         40           66.068580
39   Ketapril         45           70.662958
40   Naftisol          0           45.000000
41   Naftisol          5           46.796098
42   Naftisol         10           48.694210
43   Naftisol         15           50.933018
44   Naftisol         20           53.644087
45   Naftisol         25           56.731968
46   Naftisol         30           59.559509
47   Naftisol         35           62.685087
48   Naftisol         40           65.600754
49   Naftisol         45           69.265506

In [3]:
# Store the Standard Error of Tumor Volumes Grouped by Drug and Timepoint
std_err_grp = df.groupby(["Drug", "Timepoint"])["Tumor Volume (mm3)"].sem().reset_index()

# Convert to DataFrame
std_err_df = pd.DataFrame(std_err_grp)
# Preview DataFrame
std_err_df.head(10)

        Drug  Timepoint  Tumor Volume (mm3)
0  Capomulin          0            0.000000
1  Capomulin          5            0.448593
2  Capomulin         10            0.702684
3  Capomulin         15            0.838617
4  Capomulin         20            0.909731
5  Capomulin         25            0.881642
6  Capomulin         30            0.934460
7  Capomulin         35            1.052241
8  Capomulin         40            1.223608
9  Capomulin         45            1.223977

In [4]:
# Minor Data Munging to Re-Format the Data Frames
std_err_df = std_err_df.pivot(index="Timepoint", columns="Drug", values="Tumor Volume (mm3)")
# Preview that Reformatting worked
std_err_df.head(10)

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.448593,0.164505,0.235102,0.264819,0.202385,0.218091,0.231708,0.482955,0.239862,0.188950
10,0.702684,0.236144,0.282346,0.357421,0.319415,0.402064,0.376195,0.720225,0.433678,0.263949
15,0.838617,0.332053,0.357705,0.580268,0.444378,0.614461,0.466109,0.770432,0.493261,0.370544
20,0.909731,0.359482,0.476210,0.726484,0.595260,0.839609,0.555181,0.786199,0.621889,0.533182
25,0.881642,0.439356,0.550315,0.755413,0.813706,1.034872,0.577401,0.746991,0.741922,0.602513
30,0.934460,0.490620,0.631061,0.934121,0.975496,1.218231,0.746045,0.864906,0.899548,0.800043
35,1.052241,0.692248,0.984155,1.127867,1.013769,1.287481,1.084929,0.967433,1.003186,0.881426
40,1.223608,0.708505,1.055220,1.158449,1.118567,1.370634,1.564779,1.128445,1.410435,0.998515
45,1.223977,0.902358,1.144427,1.453186,1.416363,1.351726,1.888586,1.226805,1.576556,1.003576

In [5]:
# Generate the Plot (with Error Bars)

# Save the Figure

In [6]:
# Show the Figure
plt.show()

![Tumor Response to Treatment](../Images/treatment.png)

## Metastatic Response to Treatment

In [7]:
# Store the Mean Met. Site Data Grouped by Drug and Timepoint 
metas_treat_mean = df.groupby(["Drug", "Timepoint"])["Metastatic Sites"].mean()
# Convert to DataFrame
metas_treat_mean = pd.DataFrame(metas_treat_mean)
# Preview DataFrame
metas_treat_mean.head(10)

                     Metastatic Sites
Drug      Timepoint
Capomulin 0                  0.000000
          5                  0.160000
          10                 0.320000
          15                 0.375000
          20                 0.652174
          25                 0.818182
          30                 1.090909
          35                 1.181818
          40                 1.380952
          45                 1.476190

In [23]:
# Store the Standard Error associated with Met. Sites Grouped by Drug and Timepoint 
metas_treat_std = df.groupby(["Drug", "Timepoint"])["Metastatic Sites"].sem().reset_index()
# Convert to DataFrame
metas_treat_df = pd.DataFrame(metas_treat_std)
# Preview DataFrame
metas_treat_df.head(5)

        Drug  Timepoint  Metastatic Sites
0  Capomulin          0          0.000000
1  Capomulin          5          0.074833
2  Capomulin         10          0.125433
3  Capomulin         15          0.132048
4  Capomulin         20          0.161621

In [24]:
# Minor Data Munging to Re-Format the Data Frames
metas_treat_df = metas_treat_df.pivot(index="Timepoint", columns="Drug", values="Metastatic Sites")

# Preview that Reformatting worked
metas_treat_df

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.074833,0.108588,0.091652,0.098100,0.093618,0.100947,0.095219,0.066332,0.087178,0.077709
10,0.125433,0.152177,0.159364,0.142018,0.163577,0.115261,0.105690,0.090289,0.123672,0.109109
15,0.132048,0.180625,0.194015,0.191381,0.158651,0.190221,0.136377,0.115261,0.153439,0.111677
20,0.161621,0.241034,0.234801,0.236680,0.181731,0.234064,0.171499,0.119430,0.200905,0.166378
25,0.181818,0.258831,0.265753,0.288275,0.185240,0.263888,0.199095,0.119430,0.219824,0.236621
30,0.172944,0.249479,0.227823,0.347467,0.266667,0.300264,0.266469,0.139968,0.230641,0.248168
35,0.169496,0.266526,0.224733,0.361418,0.330464,0.341412,0.366667,0.145997,0.240983,0.285714
40,0.175610,0.289128,0.314466,0.315725,0.321702,0.297294,0.433903,0.160591,0.312815,0.299791
45,0.202591,0.286101,0.309320,0.278722,0.351104,0.304240,0.428571,0.190221,0.359062,0.286400

In [27]:
# Generate the Plot (with Error Bars)
plt.show()
# Save the Figure
metas_treat_plt = plt.show()
# Show the Figure
plt.show()

![Metastatic Spread During Treatment](../Images/spread.png)

## Survival Rates

In [38]:
# Store the Count of Mice Grouped by Drug and Timepoint (W can pass any metric)

survival_group = df.groupby(["Drug", "Timepoint"])["Mouse ID"].count().reset_index()
# Convert to DataFrame
survival_df = pd.DataFrame(survival_group).rename({"Mouse ID": "Mouse Count"}, axis=1)
# Preview DataFrame
survival_df.head(10)

        Drug  Timepoint  Mouse Count
0  Capomulin          0           25
1  Capomulin          5           25
2  Capomulin         10           25
3  Capomulin         15           24
4  Capomulin         20           23
5  Capomulin         25           22
6  Capomulin         30           22
7  Capomulin         35           22
8  Capomulin         40           21
9  Capomulin         45           21

In [40]:
# Minor Data Munging to Re-Format the Data Frames
survival_df = survival_df.pivot(index="Timepoint", columns="Drug", values="Mouse Count")
# Preview the Data Frame
survival_df

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,25,25,25,25,25,25,26,25,26,25
5,25,21,25,23,23,24,25,25,25,24
10,25,20,21,22,21,24,23,24,23,22
15,24,19,21,19,21,20,17,24,23,21
20,23,18,20,19,20,19,17,23,21,17
25,22,18,18,19,18,17,14,23,19,16
30,22,16,17,18,15,15,13,23,18,15
35,22,14,12,17,15,14,10,21,16,14
40,21,14,10,15,15,12,9,20,12,14
45,21,13,9,11,13,11,7,20,11,14

In [41]:
# Generate the Plot (Accounting for percentages)

# Save the Figure

# Show the Figure
plt.show()

![Metastatic Spread During Treatment](../Images/survival.png)

## Summary Bar Graph

In [ ]:
# Calculate the percent changes for each drug

# Display the data to confirm

In [ ]:
# Store all Relevant Percent Changes into a Tuple


# Splice the data between passing and failing drugs


# Orient widths. Add labels, tick marks, etc. 


# Use functions to label the percentages of changes


# Call functions to implement the function calls


# Save the Figure


# Show the Figure
fig.show()

![Metastatic Spread During Treatment](../Images/change.png)